global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "sentiment-api"
    static_configs:
      - targets: ["app:8000"]
    metrics_path: "/metrics"

  - job_name: "mlflow"
    static_configs:
      - targets: ["mlflow:5003"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  - "alert.yml"
