model:
  base_model: "distilbert-base-uncased"
  max_length: 512
  num_labels: 2

training:
  output_dir: "./models/sentiment"
  epochs: 3
  batch_size: 16
  warmup_steps: 500
  weight_decay: 0.01
  learning_rate: 2e-5

evaluation:
  eval_steps: 500
  save_steps: 1000
  logging_steps: 100

data:
  dataset: "glue"
  task: "sst2"
  train_split: "train"
  eval_splits: "validation"
